# Generated by Django 4.2.7 on 2023-11-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.CharField(max_length=500, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='изображение')),
                ('category', models.CharField(max_length=100, verbose_name='категория')),
                ('price_for_one', models.FloatField(verbose_name='цена за штуку')),
                ('date_of_creation', models.DateTimeField(verbose_name='дата создания')),
                ('last_modified_date', models.DateTimeField(verbose_name='дата последнего изменения, **NULLABLE')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('description',),
            },
        ),
    ]
