# Generated by Django 4.2.7 on 2023-11-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_category_product_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_for_one',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=None, max_length=100, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_creation',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_modified_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='дата последнего изменения'),
        ),
    ]
